sudo: required
service:
 - docker
before_install:
  - docker build -t senduraselvan/custom2:v4.0 .
script:
 - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
 - docker images # to verify image is build or not
 - docker push senduraselvan/custom2:v4.0
notifications:
 email:
   recipients:
     - sendura28@gmail.com
   on_success: always
   on_failure: always
